
package br.edu.qi.webserver.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdocaoServiceService", targetNamespace = "http://service.soap.webserver.qi.edu.br/", wsdlLocation = "http://localhost/8081/adocaoWs?wsdl")
public class AdocaoServiceService
    extends Service
{

    private final static URL ADOCAOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADOCAOSERVICESERVICE_EXCEPTION;
    private final static QName ADOCAOSERVICESERVICE_QNAME = new QName("http://service.soap.webserver.qi.edu.br/", "AdocaoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/8081/adocaoWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADOCAOSERVICESERVICE_WSDL_LOCATION = url;
        ADOCAOSERVICESERVICE_EXCEPTION = e;
    }

    public AdocaoServiceService() {
        super(__getWsdlLocation(), ADOCAOSERVICESERVICE_QNAME);
    }

    public AdocaoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADOCAOSERVICESERVICE_QNAME, features);
    }

    public AdocaoServiceService(URL wsdlLocation) {
        super(wsdlLocation, ADOCAOSERVICESERVICE_QNAME);
    }

    public AdocaoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADOCAOSERVICESERVICE_QNAME, features);
    }

    public AdocaoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdocaoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAdocaoService
     */
    @WebEndpoint(name = "AdocaoServicePort")
    public IAdocaoService getAdocaoServicePort() {
        return super.getPort(new QName("http://service.soap.webserver.qi.edu.br/", "AdocaoServicePort"), IAdocaoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAdocaoService
     */
    @WebEndpoint(name = "AdocaoServicePort")
    public IAdocaoService getAdocaoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.webserver.qi.edu.br/", "AdocaoServicePort"), IAdocaoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADOCAOSERVICESERVICE_EXCEPTION!= null) {
            throw ADOCAOSERVICESERVICE_EXCEPTION;
        }
        return ADOCAOSERVICESERVICE_WSDL_LOCATION;
    }

}
