
package br.edu.qi.webserver.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnimalServiceService", targetNamespace = "http://service.soap.webserver.qi.edu.br/", wsdlLocation = "http://localhost/8081/animalWs?wsdl")
public class AnimalServiceService
    extends Service
{

    private final static URL ANIMALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ANIMALSERVICESERVICE_EXCEPTION;
    private final static QName ANIMALSERVICESERVICE_QNAME = new QName("http://service.soap.webserver.qi.edu.br/", "AnimalServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/8081/animalWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANIMALSERVICESERVICE_WSDL_LOCATION = url;
        ANIMALSERVICESERVICE_EXCEPTION = e;
    }

    public AnimalServiceService() {
        super(__getWsdlLocation(), ANIMALSERVICESERVICE_QNAME);
    }

    public AnimalServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANIMALSERVICESERVICE_QNAME, features);
    }

    public AnimalServiceService(URL wsdlLocation) {
        super(wsdlLocation, ANIMALSERVICESERVICE_QNAME);
    }

    public AnimalServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANIMALSERVICESERVICE_QNAME, features);
    }

    public AnimalServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnimalServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAnimalService
     */
    @WebEndpoint(name = "AnimalServicePort")
    public IAnimalService getAnimalServicePort() {
        return super.getPort(new QName("http://service.soap.webserver.qi.edu.br/", "AnimalServicePort"), IAnimalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAnimalService
     */
    @WebEndpoint(name = "AnimalServicePort")
    public IAnimalService getAnimalServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.webserver.qi.edu.br/", "AnimalServicePort"), IAnimalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANIMALSERVICESERVICE_EXCEPTION!= null) {
            throw ANIMALSERVICESERVICE_EXCEPTION;
        }
        return ANIMALSERVICESERVICE_WSDL_LOCATION;
    }

}
