
package br.edu.qi.webserver.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAdocaoService", targetNamespace = "http://service.soap.webserver.qi.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAdocaoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.qi.webserver.soap.service.RetornoAdocaoService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adotarAnimal", targetNamespace = "http://service.soap.webserver.qi.edu.br/", className = "br.edu.qi.webserver.soap.service.AdotarAnimal")
    @ResponseWrapper(localName = "adotarAnimalResponse", targetNamespace = "http://service.soap.webserver.qi.edu.br/", className = "br.edu.qi.webserver.soap.service.AdotarAnimalResponse")
    @Action(input = "http://service.soap.webserver.qi.edu.br/IAdocaoService/adotarAnimalRequest", output = "http://service.soap.webserver.qi.edu.br/IAdocaoService/adotarAnimalResponse")
    public RetornoAdocaoService adotarAnimal(
        @WebParam(name = "arg0", targetNamespace = "")
        AdocaoServiceDto arg0);

}
